version: '3.8'

services:
  postgres_auth:
    image: postgres:latest
    container_name: postgres_auth
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - orchestrator-saga
    volumes:
      - postgres_auth_data:/var/lib/postgresql/data

  auth-service:
    build: ./auth-service
    container_name: auth-service
    depends_on:
      - postgres_auth
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_auth:5432/auth_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - "8080:8080"
    networks:
      - orchestrator-saga

  postgres_account:
    image: postgres:15
    container_name: postgres_account
    environment:
      POSTGRES_DB: account_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5433:5432"
    networks:
      - orchestrator-saga
    volumes:
      - postgres_account_data:/var/lib/postgresql/data

  account-service:
    build: ./account-service
    container_name: account-service
    depends_on:
      - postgres_account
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_account:5432/account_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
    ports:
      - "8081:8081"
    networks:
      - orchestrator-saga

networks:
  orchestrator-saga:
    driver: bridge

volumes:
  postgres_auth_data:
  postgres_account_data:
